### ISSUE TITLE
[Bug][Grid] Not all interfaces from the documentation are exported in the Grid package 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#2497]
## I'm submitting a...
* Regression report
* 
## Current behavior
Not all interfaces from the Grid API are exported. For example, GridColumnMenuColumnProps and GridRowType could not be used, but they are listed in the documentation:
 [https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnMenuColumnProps/](https://www.telerik.com/kendo-react-ui/components/grid/api/GridColumnMenuColumnProps/)
[https://www.telerik.com/kendo-react-ui/components/grid/api/GridRowType/](https://www.telerik.com/kendo-react-ui/components/grid/api/GridRowType/)

## Expected behavior
All interfaces should be exported with the package

Package versions:
8.2.0

**Comment by kdikov82** [comment]
The issue is observed after upgrading from 7.2.3 to 8.2.0 with the following errors:
```
error TS2307: Cannot find module '@progress/kendo-react-grid/interfaces/GridColumnMenuColumnProps' or its corresponding type declarations.

error TS2307: Cannot find module '@progress/kendo-react-grid/interfaces/GridRowType' or its corresponding type declarations.
```
